audit_header: false
title: Iowa's Best Real Estate Training - Holly Brink
description: >-
  Holly Brink, Designated Managing Broker of over 115+ eXp Realty Iowa agents,
  shares her top real estate agent training for FREE. Her Free Real Estate
  Training, Tips, and Advice will help also “Hustle” in Real Estate.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: 'https://www.eventbrite.com/o/28074168105'
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/
client:
  name: Holly Brink
  title:
  license_number:
  about_markdown: >-
    Hustle with Holly is a show hosted by Holly Brink, Designated Managing
    Broker of eXp Realty Iowa. With great, actionable ideas and interviews with
    eXperts across the board it’s a great way for brand new & experienced agents
    to take their business to the neXt level as well as find out more about eXp
    Realty.&nbsp;


    All opinions are those of the host and guests, respectively, not those of
    eXp Realty.&nbsp;


    For more information about joining Holly’s Worldwide Organization within eXp
    Realty go to: FreeRealEstateAgentTraining.com or JoinHollyBrink.com
  market: Iowa
  brand: eXp Realty
  brokerage:
  address: >-
    Spencer, Iowa<br>Holly Brink is licensed to practice<br>real estate in Iowa
    & Arizona<br>EXP Realty is located in all 50 US States,<br>Canada, Australia
    and the U.K<br><a
    href="https://hollybrink.exprealty.com/ask/45cea0f269759ea4fcfa4e363a0d856a">Get
    Your Free Virtual Training Pass</a>
  phone: 712-363-2399
  phone_type:
  phone2:
  phone2_type:
  email: holly.brink@exprealty.com
  url: 'http://www.ThinkHousesThinkHolly.com'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: Looking to Build Your Real Estate Career?
    CTA_text: Let's talk about how eXp Realty can take your business to new heights.
    CTA_link_text: Free Strategy Session
    CTA_url: /contact/
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
socials:
  review_sm_icons: false
  facebook_url: 'http://www.facebook.com/thinkhousesthinkholly'
  linkedin_url: 'https://www.linkedin.com/in/mrshollybrink'
  gplus_url:
  youtube_url: 'https://www.youtube.com/channel/UChBwC2ZX8J-kK4q81A6omoA'
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Hustle With Holly
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Iowa Area
    Real Estate Market
  description: >-
    Hustle with Holly is a show hosted by Holly Brink, Designated Managing Broker of eXp Realty Iowa. With great, actionable ideas and interviews with eXperts across the board it’s a great way for brand new & experienced agents to take their business to the neXt level as well as find out more about eXp Realty.

    All opinions are those of the host and guests, respectively, not those of eXp Realty.

    For more information about joining Holly’s Worldwide Organization within eXp Realty go to: FreeRealEstateAgentTraining.com or JoinHollyBrink.com
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Iowa, home
    selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Holly Brink
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Iowa Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#f9a81a'
  theme_color: '#19469d'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: 'rgba(0, 0, 0, 0)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
